/**
 * controllers/analyticsController.js
 * Serves analytics data: KPIs, ABC analysis, forecasts, trends, alerts.
 * Reads from pre-computed JSON (generated by Python engine) with DB fallback.
 */
const path   = require("path");
const fs     = require("fs");
const pool   = require("../config/database");
const logger = require("../utils/logger");

const DATA_PATH = path.resolve(
  process.env.ANALYTICS_DATA_DIR || "../python-analytics/data",
  "analytics_results.json"
);

// Cache analytics in memory, refresh every 10 minutes
let _analyticsCache   = null;
let _cacheTimestamp   = null;
const CACHE_TTL_MS    = 10 * 60 * 1000;

const getAnalytics = () => {
  if (_analyticsCache && Date.now() - _cacheTimestamp < CACHE_TTL_MS) {
    return _analyticsCache;
  }
  try {
    const raw = fs.readFileSync(DATA_PATH, "utf8");
    _analyticsCache  = JSON.parse(raw);
    _cacheTimestamp  = Date.now();
    return _analyticsCache;
  } catch {
    return null;
  }
};

// ── GET /api/analytics/kpis ──────────────────────────────────
const getKpis = async (req, res) => {
  try {
    const analytics = getAnalytics();
    if (analytics?.kpis) {
      return res.json({ success: true, data: analytics.kpis });
    }

    // DB fallback
    const [[kpis]] = await pool.query(`
      SELECT
        ROUND(SUM(s.total_amount), 2)               AS total_revenue_inr,
        ROUND(SUM(p.quantity_in_stock * p.cost_price), 2) AS inventory_value_inr,
        SUM(CASE WHEN p.quantity_in_stock <= p.reorder_level THEN 1 ELSE 0 END) AS low_stock_items,
        COUNT(DISTINCT p.id)                        AS total_products,
        COUNT(DISTINCT s.id)                        AS total_sales_records
      FROM products p
      LEFT JOIN sales s ON s.product_id = p.id
      WHERE p.is_active = 1
    `);

    return res.json({ success: true, data: kpis });
  } catch (err) {
    logger.error(`getKpis: ${err.message}`);
    return res.status(500).json({ success: false, message: "Failed to fetch KPIs" });
  }
};

// ── GET /api/analytics/abc ───────────────────────────────────
const getAbc = async (req, res) => {
  try {
    const analytics = getAnalytics();
    if (analytics?.abc_analysis) {
      return res.json({ success: true, data: analytics.abc_analysis });
    }
    return res.status(503).json({ success: false, message: "Analytics not yet computed" });
  } catch (err) {
    logger.error(`getAbc: ${err.message}`);
    return res.status(500).json({ success: false, message: "Failed to fetch ABC analysis" });
  }
};

// ── GET /api/analytics/trends ────────────────────────────────
const getTrends = async (req, res) => {
  try {
    const { period = "daily" } = req.query;
    const analytics = getAnalytics();

    if (analytics?.sales_trends?.[period]) {
      return res.json({ success: true, data: analytics.sales_trends[period] });
    }

    // DB fallback for daily
    const [rows] = await pool.query(`
      SELECT
        DATE_FORMAT(sale_date, '%Y-%m-%d') AS sale_date,
        ROUND(SUM(total_amount), 2)        AS revenue_inr,
        SUM(quantity_sold)                 AS units_sold
      FROM sales
      WHERE sale_date >= DATE_SUB(CURDATE(), INTERVAL 90 DAY)
      GROUP BY sale_date
      ORDER BY sale_date
    `);

    return res.json({ success: true, data: rows });
  } catch (err) {
    logger.error(`getTrends: ${err.message}`);
    return res.status(500).json({ success: false, message: "Failed to fetch trends" });
  }
};

// ── GET /api/analytics/dos ───────────────────────────────────
const getDaysOfSupply = async (req, res) => {
  try {
    const analytics = getAnalytics();
    if (analytics?.days_of_supply) {
      return res.json({ success: true, data: analytics.days_of_supply });
    }
    return res.status(503).json({ success: false, message: "Analytics not yet computed" });
  } catch (err) {
    logger.error(`getDOS: ${err.message}`);
    return res.status(500).json({ success: false, message: "Failed to fetch DOS" });
  }
};

// ── GET /api/analytics/forecasts ─────────────────────────────
const getForecasts = async (req, res) => {
  try {
    const analytics = getAnalytics();
    if (analytics?.demand_forecasts) {
      return res.json({ success: true, data: analytics.demand_forecasts });
    }
    return res.status(503).json({ success: false, message: "Forecasts not yet computed" });
  } catch (err) {
    logger.error(`getForecasts: ${err.message}`);
    return res.status(500).json({ success: false, message: "Failed to fetch forecasts" });
  }
};

// ── GET /api/analytics/recommendations ───────────────────────
const getRecommendations = async (req, res) => {
  try {
    const analytics = getAnalytics();
    if (analytics?.restock_recommendations) {
      return res.json({ success: true, data: analytics.restock_recommendations });
    }
    return res.status(503).json({ success: false, message: "Recommendations not yet computed" });
  } catch (err) {
    logger.error(`getRecommendations: ${err.message}`);
    return res.status(500).json({ success: false, message: "Failed to fetch recommendations" });
  }
};

// ── GET /api/analytics/category-distribution ─────────────────
const getCategoryDistribution = async (req, res) => {
  try {
    const [rows] = await pool.query(`
      SELECT
        c.id, c.name AS category,
        COUNT(DISTINCT p.id)                            AS product_count,
        ROUND(SUM(s.total_amount), 2)                   AS revenue_inr,
        ROUND(SUM(s.total_amount) / SUM(SUM(s.total_amount)) OVER() * 100, 2) AS revenue_pct
      FROM categories c
      LEFT JOIN products p ON p.category_id = c.id AND p.is_active = 1
      LEFT JOIN sales    s ON s.product_id  = p.id
      GROUP BY c.id, c.name
      ORDER BY revenue_inr DESC
    `);
    return res.json({ success: true, data: rows });
  } catch (err) {
    logger.error(`getCategoryDist: ${err.message}`);
    return res.status(500).json({ success: false, message: "Failed to fetch category data" });
  }
};

// ── GET /api/analytics/stock-classification ──────────────────
const getStockClassification = async (req, res) => {
  try {
    const analytics = getAnalytics();
    if (analytics?.stock_classification) {
      return res.json({ success: true, data: analytics.stock_classification });
    }
    return res.status(503).json({ success: false, message: "Stock classification not computed" });
  } catch (err) {
    logger.error(`getStockClassification: ${err.message}`);
    return res.status(500).json({ success: false, message: "Failed" });
  }
};

// ── POST /api/analytics/refresh ──────────────────────────────
const refreshAnalytics = async (req, res) => {
  try {
    const { exec } = require("child_process");
    const scriptPath = path.resolve(
      process.env.ANALYTICS_SCRIPT || "../python-analytics/analytics_engine.py"
    );
    const pythonBin = process.env.PYTHON_BIN || "python3";

    exec(`${pythonBin} ${scriptPath}`, (error, stdout, stderr) => {
      if (error) {
        logger.error(`Analytics refresh failed: ${error.message}`);
        return res.status(500).json({ success: false, message: "Analytics refresh failed", error: error.message });
      }
      // Invalidate cache
      _analyticsCache = null;
      _cacheTimestamp = null;
      logger.info("Analytics refreshed via API call");
      return res.json({ success: true, message: "Analytics refreshed successfully", output: stdout });
    });
  } catch (err) {
    logger.error(`refreshAnalytics: ${err.message}`);
    return res.status(500).json({ success: false, message: "Failed to trigger refresh" });
  }
};

module.exports = {
  getKpis, getAbc, getTrends, getDaysOfSupply, getForecasts,
  getRecommendations, getCategoryDistribution, getStockClassification,
  refreshAnalytics,
};
